// Context Injector — Phase 2
// Writes task context files into worktree directories
// so AI agents can pick up task descriptions and prompts.

import * as fs from 'fs/promises';
import * as path from 'path';
import { log } from '../utils/logger';

export interface TaskContext {
  description: string;
  issueUrl?: string;
  prompt?: string;
}

export class ContextInjector {
  private static readonly CONTEXT_FILE = '.claude-task-context.md';

  async inject(worktreePath: string, context: TaskContext): Promise<void> {
    const filePath = path.join(worktreePath, ContextInjector.CONTEXT_FILE);

    const content = [
      '# Task Context',
      '',
      `## Description`,
      context.description,
      '',
      context.issueUrl ? `## Issue\n${context.issueUrl}\n` : '',
      context.prompt ? `## Prompt\n${context.prompt}\n` : '',
      '---',
      '_Generated by GitFlow Studio_',
    ]
      .filter(Boolean)
      .join('\n');

    await fs.writeFile(filePath, content, 'utf-8');
    log(`[AI] Injected context into ${filePath}`);
  }

  async remove(worktreePath: string): Promise<void> {
    const filePath = path.join(worktreePath, ContextInjector.CONTEXT_FILE);
    try {
      await fs.unlink(filePath);
      log(`[AI] Removed context from ${filePath}`);
    } catch {
      // File doesn't exist, ignore
    }
  }
}
